repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: double-quote-string-fixer
-   repo: local
    hooks:
    -   id: isort
        name: Sort imports
        entry: isort --settings-path=.isort.cfg
        language: system
        types:
            - python
    -   id: black
        name: Check with black
        entry: black -S
        language: system
        types:
            - python
    -   id: flake8
        name: flake8
        entry: flake8 --config=.flake8
        language: system
        types:
            - python
